server:
  port: 80
  servlet:
    session:
      cookie:
        name: sid
      timeout: 1d
logging:
  file:
    path: log
    max-history: 30

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bright_storage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: lcpw_845
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 3MB
  data:
    redis:
      repositories:
        enabled: false

bright-storage:
  file:
    root: [.bright_storage, uploads]
    # 必须以'/'开头
    virtual: /uploads
    options:
      avatar: {path: [img], type: avatar, thumbnail: true, width: 200, height: 200}
      cover: {path: [img], type: cover}
      image: {path: [img], type: image}
      file: {path: [common], type: file}

